# Generated by Django 3.2.12 on 2022-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsg',
            name='send_time',
            field=models.DateTimeField(),
        ),
    ]
