# Generated by Django 3.2.13 on 2022-06-09 15:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('like_count', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.board')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user'),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hamlet.board')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
        migrations.CreateModel(
            name='BanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
    ]
