# Generated by Django 3.2.13 on 2022-06-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamlet.user')),
            ],
        ),
    ]
