# Generated by Django 3.2.13 on 2022-06-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamlet', '0002_auto_20220610_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_time',
        ),
    ]
