# Generated by Django 3.2.12 on 2022-06-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamlet', '0003_auto_20220612_1018'),
        ('hamlet', '0014_delete_chatmsg'),
    ]

    operations = [
    ]
